version: "3"

services:
  mysql-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - local-dev
    environment:
      MYSQL_DATABASE: "security"
      MYSQL_USER: "aplicacao"
      MYSQL_PASSWORD: "aplicacao"
      MYSQL_ROOT_PASSWORD : "root"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
networks:
  local-dev:
    driver: bridge